project:
  type: website
  output-dir: docs

website:
  title: "Farm Precip."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: documentation.qmd
        text: Documentation
      - href: tutorial.qmd
        text: Tutorial
      - href: technicalwriteup.qmd
        text: Technical Writeup

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



